/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-error-container": "#ffdad6",
        "on-secondary-fixed": "#041b3a",
        "primary-fixed-dim": "#ffb2bb",
        "secondary-container": "#36496b",
        "surface-container-high": "#2a2a2a",
        "on-secondary-fixed-variant": "#344768",
        "electric-crimson": "#FF005E",
        "secondary-fixed-dim": "#b3c7ef",
        "on-tertiary": "#00391e",
        "surface-container-low": "#1b1b1b",
        "on-primary-fixed-variant": "#910032",
        "on-secondary-container": "#a5b9e0",
        "outline-variant": "#5d3e42",
        "secondary-fixed": "#d6e3ff",
        "tertiary": "#67dd97",
        "secondary": "#b3c7ef",
        "error-pure": "#EF4444",
        "on-surface-variant": "#e7bcc0",
        "surface-container-lowest": "#0e0e0e",
        "primary-fixed": "#ffd9dc",
        "surface-variant": "#353535",
        "error-container": "#93000a",
        "surface-dim": "#131313",
        "surface-bright": "#393939",
        "outline": "#ae878b",
        "surface-light": "#141414",
        "on-tertiary-fixed-variant": "#00522d",
        "on-secondary": "#1c3050",
        "border-muted": "#1F2937",
        "on-error": "#690005",
        "error": "#ffb4ab",
        "on-tertiary-container": "#003119",
        "tertiary-fixed": "#84fab1",
        "on-surface": "#e2e2e2",
        "on-tertiary-fixed": "#00210f",
        "deep-emerald": "#059669",
        "inverse-on-surface": "#303030",
        "inverse-surface": "#e2e2e2",
        "on-primary-fixed": "#400011",
        "tertiary-container": "#25a565",
        "on-primary": "#670021",
        "surface-tint": "#ffb2bb",
        "inverse-primary": "#bd0044",
        "on-primary-container": "#5a001c",
        "surface-container-highest": "#353535",
        "tertiary-fixed-dim": "#67dd97",
        "on-background": "#e2e2e2",
        "surface-container": "#1f1f1f",
        "primary": "#ffb2bb",
        "surface": "#131313",
        "primary-container": "#ff4f74",
        "surface-dark": "#0A0A0A",
        "background": "#131313",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "margin-mobile": "16px",
        "unit": "4px",
        "margin-desktop": "32px",
        "gutter": "16px",
        "panel-padding": "24px",
      },
      fontFamily: {
        "body-md": ["Inter"],
        "label-caps": ["Inter"],
        "data-tabular": ["JetBrains Mono"],
        "display-lg": ["Inter"],
        "headline-md": ["Inter"],
        "headline-md-mobile": ["Inter"],
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "data-tabular": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-md-mobile": ["20px", { lineHeight: "28px", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
}